-- luacheck configuration, run from the repository root: luacheck .
-- Only syntax errors and global variables are checked: a new global read or write is either a typo or an API
-- that must be checked on WoW Forever first. Once checked, add it to the list below.
std = "lua51"
only = { "011", "1" }
-- Fields of standard tables: WoW adds its own (string.split, table.wipe...)
ignore = { "14." }
exclude_files = { "**/Libs/**", ".claude/**", "**/.claude/**" }

-- Every global the addons read or write, sorted
globals = {
  "AnchorUtil", "AuraContainerSortDirection", "AuraContainerSortMethod", "C_AuraContainerUtil", "C_EditMode",
  "ColorPickerFrame", "CooldownViewerDataStoreSerializationMixin", "CooldownViewerLayoutManagerMixin",
  "CooldownViewerSettings", "CooldownViewerSettingsDataProviderMixin", "CustomAuraContainerAuraProcessingPolicy",
  "EditModeManagerFrame", "EditModePresetLayoutManager", "EventRegistry", "FojjiCore", "FojjiCoreDB", "GetTotemInfo",
  "LATER", "LOCALIZED_CLASS_NAMES_MALE", "PixelUtil", "RELOADUI", "ReloadUI", "UnitIsFriend", "UnitPowerType",
  "UnitStat",
  "AbbreviateLargeNumbers", "AbbreviateNumbers", "abs", "ACCEPT", "AceGUIWeakAurasInputWithIndentationInsertLink",
  "AceGUIWeakAurasMultiLineEditBoxInsertLink", "AceGUIWeakAurasMultiLineEditBoxWithEnterInsertLink",
  "AceGUIWidgetLSMlists", "AddonCompartmentFrame", "Ambiguate", "AMMOSLOT", "APIDocumentation",
  "APIDocumentation_LoadUI", "atan2", "AuraUtil", "BackdropTemplateMixin", "BACKSLOT", "BigWigs", "BigWigsLoader",
  "BINDING_HEADER_RAID_TARGET", "BINDING_HEADER_WEAKAURAS", "BINDING_NAME_WEAKAURASPRINTPROFILING",
  "BINDING_NAME_WEAKAURASPROFILINGTOGGLE", "BINDING_NAME_WEAKAURASTOGGLE", "bit", "BNGetFriendGameAccountInfo",
  "BNGetNumFriendGameAccounts", "BNGetNumFriends", "BreakUpLargeNumbers", "BURNING_EMBERS",
  "ButtonFrameTemplate_HidePortrait", "C_AddOns", "C_AssistedCombat", "C_BattleNet", "C_ChallengeMode", "C_ChatInfo",
  "C_ClassTalents", "C_CombatLog", "C_Container", "C_CooldownViewer", "C_Covenants", "C_CreatureInfo", "C_CurrencyInfo", "C_CurveUtil", "C_CVar", "CurveConstants", "C_DurationUtil",
  "C_DamageMeter", "C_DateAndTime", "ceil", "C_EncounterJournal", "C_Engraving", "C_EquipmentSet", "C_GamePad",
  "C_GameRules", "C_GossipInfo", "ChatConfigFrame", "ChatConfigFrameChatTabManager", "ChatFontNormal",
  "ChatFrame_AddMessageEventFilter", "CHESTSLOT", "CHI_POWER", "C_Item", "Clamp", "ClearCursor", "C_MajorFactions",
  "C_Map", "C_Minimap", "C_NamePlate", "CollapseFactionHeader", "ColorMixin", "CombatLogGetCurrentEventInfo",
  "COMBATLOG_OBJECT_AFFILIATION_MINE", "COMBATLOG_OBJECT_AFFILIATION_OUTSIDER", "COMBATLOG_OBJECT_AFFILIATION_PARTY",
  "COMBATLOG_OBJECT_RAIDTARGET_MASK", "CombatText_AddMessage", "COMBAT_TEXT_SCROLL_FUNCTION", "COMBO_POINTS",
  "COOKINGGEAR0SLOT", "COOKINGTOOLSLOT", "CopyTable", "cos", "C_PetBattles", "C_PvP", "CreateAtlasMarkup",
  "CreateColor", "CreateColorFromHexString", "CreateDataProvider", "CreateFont", "CreateFrame", "CreateFramePool",
  "CreateFromMixins", "CreateObjectPool", "CreateScrollBoxListLinearView", "CreateTextureMarkup", "CreateVector3D",
  "C_Reputation", "CR_HIT_MELEE", "CR_HIT_RANGED", "CR_HIT_SPELL", "C_Seasons", "C_Secrets", "C_SpecializationInfo",
  "C_Spell", "C_SpellBook", "C_StringUtil", "C_SwingTimer", "C_Texture", "C_Timer", "C_TooltipInfo", "C_Traits", "C_UnitAuras",
  "CUSTOM_CLASS_COLORS", "DAMAGER", "date", "DBM", "DBT", "debugprofilestop", "debugstack", "DEFAULT_CHAT_FRAME",
  "DevTools_Dump", "ECLIPSE", "ElvUI", "ElvUIPlayerNamePlateAnchor", "ENABLE_AMBIENCE", "ENABLE_DIALOG",
  "ENABLE_MUSIC", "ENABLE_SOUNDFX", "Enum", "ExpandCurrencyList", "ExpandFactionHeader", "FEETSLOT",
  "FindBaseSpellByID", "FindSpellOverrideByID", "FINGER0SLOT_UNIQUE", "FINGER1SLOT_UNIQUE", "FISHINGTOOLSLOT",
  "floor", "FONT_COLOR_CODE_CLOSE", "format", "FrameDeltaLerp", "GameFontHighlight", "GameFontHighlightLarge",
  "GameFontNormal", "GameFontNormalHuge", "GameFontNormalLarge", "GameFontNormalSmall", "GameFontNormalSmall2",
  "GAME_LOCALE", "GameTooltip", "GetAchievementInfo", "GetActiveTalentGroup", "GetArenaOpponentSpec", "GetAtlasInfo",
  "GetBuildInfo", "GetCategoryList", "GetCategoryNumAchievements", "GetClassAtlas", "GetClassInfo",
  "GetCombatRatingBonus", "GetCritChance", "GetCurrencyListInfo", "GetCurrencyListSize", "GetCurrentKeyBoardFocus",
  "GetCurrentRegion", "GetCursorInfo", "GetCursorPosition", "GetCVar", "GetDifficultyInfo", "geterrorhandler",
  "GetFactionInfo", "GetFactionInfoByID", "GetFileIDFromPath", "GetFrameCPUUsage", "GetGlyphSocketInfo",
  "GetGuildInfo", "GetHaste", "GetHitModifier", "GetInstanceInfo", "GetInventoryItemDurability", "GetInventoryItemCooldown", "GetInventoryItemID",
  "GetInventoryItemLink", "GetInventoryItemTexture", "GetInventorySlotInfo", "GetLocale", "GetMacroInfo",
  "GetMinimapZoneText", "GetMoney", "GetMouseFoci", "GetMouseFocus", "GetNumClasses", "GetNumFactions",
  "GetNumGroupMembers", "GetNumShapeshiftForms", "GetNumSpecializationsForClassID", "GetNumSubgroupMembers",
  "GetNumTalents", "GetNumTalentTabs", "GetPhysicalScreenSize", "GetPlayerInfoByGUID", "GetPowerRegenForPowerType",
  "GetPvpTalentInfoByID", "GetRaidRosterInfo", "GetRaidTargetIndex", "GetRangedCritChance", "GetRealmName",
  "GetRealZoneText", "GetRuneCooldown", "GetRuneType", "GetScreenHeight", "GetScreenWidth", "GetShapeshiftForm",
  "GetShapeshiftFormID", "GetShapeshiftFormInfo", "GetSpecialization", "GetSpecializationInfo",
  "GetSpecializationInfoByID", "GetSpecializationInfoForClassID", "GetSpellBonusDamage", "GetSpellCharges",
  "GetSpellCount", "GetSpellCritChance", "GetSpellDescription", "GetSpellHitModifier", "GetSpellInfo",
  "GetSpellLink", "GetSpellLossOfControlCooldown", "GetSpellTexture", "GetTalentGroupRole", "GetTexCoordsByGrid",
  "GetText", "GetTime", "GetTotemDuration", "GetUnitEmpowerHoldAtMaxTime", "GetUnitName", "GetUnitSpeed", "GetWatchedFactionInfo",
  "GetWeaponEnchantInfo", "gsub", "HANDSSLOT", "HasOverrideActionBar", "HasVehicleActionBar", "HEADSLOT", "HEALER",
  "HOLY_POWER", "hooksecurefunc", "ICON_LIST", "ICON_TAG_LIST", "InCombatLockdown", "IndentationLib", "INVSLOT_AMMO", "INVSLOT_FIRST_EQUIPPED", "INVSLOT_LAST_EQUIPPED",
  "INLINE_DAMAGER_ICON", "INLINE_HEALER_ICON", "INLINE_TANK_ICON", "ipairs_reverse", "IsArenaSkirmish",
  "IsControlKeyDown", "IsGuildMember", "IsInGroup", "IsInInstance", "IsInRaid", "IsMounted", "IsMouseButtonDown",
  "IsPlayerMoving", "IsPlayerSpell", "issecretvalue", "IsShiftKeyDown", "IsSpellKnown", "IsUsableSpell", "Item",
  "ItemLocationMixin", "ItemRefTooltip", "ItemTransmogInfoMixin", "KuiNameplatesCore", "KuiNameplatesPlayerAnchor",
  "LARGE_NUMBER_SEPERATOR", "LEGSSLOT", "LE_PARTY_CATEGORY_INSTANCE", "Lerp", "LE_UNIT_STAT_AGILITY", "LibStub",
  "LOWER_LEFT_VERTEX", "LOWER_RIGHT_VERTEX", "MAINASSIST", "MAINHANDSLOT", "MAINTANK", "max", "MAX_NUM_TALENTS",
  "MAX_SPELL_SCHOOLS", "MAX_TALENT_TIERS", "MenuUtil", "MergeTable", "min", "Mixin", "MONEY", "MouseIsOver",
  "NamePlateDriverFrame", "NECKSLOT", "NORMAL_FONT_COLOR", "NUM_BAG_SLOTS", "NUM_GLYPH_SLOTS", "NUM_TALENT_COLUMNS", "OKAY", "OmniCC",
  "PET_MODE_AGGRESSIVE", "PET_MODE_ASSIST", "PET_MODE_DEFENSIVE", "PET_MODE_PASSIVE", "Plater", "PLAYER_DIFFICULTY1",
  "PLAYER_DIFFICULTY2", "PLAYER_DIFFICULTY3", "PLAYER_DIFFICULTY5", "PLAYER_DIFFICULTY6",
  "PLAYER_DIFFICULTY_TIMEWALKER", "PlayerLocationMixin", "PlaySound", "PlaySoundFile", "PowerBarColor",
  "POWER_TYPE_ARCANE_CHARGES", "POWER_TYPE_DEMONIC_FURY", "POWER_TYPE_ENERGY", "POWER_TYPE_ESSENCE",
  "POWER_TYPE_FOCUS", "POWER_TYPE_FURY_DEMONHUNTER", "POWER_TYPE_INSANITY", "POWER_TYPE_LUNAR_POWER",
  "POWER_TYPE_MAELSTROM", "POWER_TYPE_MANA", "POWER_TYPE_PAIN", "POWER_TYPE_RED_POWER", "rad", "RAID_CLASS_COLORS",
  "RAID_TARGET_1", "RAID_TARGET_2", "RAID_TARGET_3", "RAID_TARGET_4", "RAID_TARGET_5", "RAID_TARGET_6",
  "RAID_TARGET_7", "RAID_TARGET_8", "RAID_TARGET_NONE", "random", "RANGEDSLOT", "RELICSLOT", "ResetCursor", "Round",
  "RUNIC_POWER", "SafePack", "SafeUnpack", "Saturate", "ScrollUtil", "SearchBoxTemplate_OnTextChanged",
  "SECONDARYHANDSLOT", "SecondsFormatter", "SecondsFormatterMixin", "SecondsToTimeAbbrev", "SendChatMessage",
  "SetCursor", "SHADOW_ORBS", "SHOULDERSLOT", "ShowUIPanel", "sin", "SlashCmdList", "SLASH_WEAKAURAS1",
  "SLASH_WEAKAURAS2", "sort", "SOUL_SHARDS_POWER", "SPECIALIZATION", "Spell", "sqrt", "STAGGER",
  "STANDARD_TEXT_FONT", "StaticPopupDialogs", "StaticPopup_Show", "StopSound",
  "STRING_ENVIRONMENTAL_DAMAGE_DROWNING", "STRING_ENVIRONMENTAL_DAMAGE_FALLING",
  "STRING_ENVIRONMENTAL_DAMAGE_FATIGUE", "STRING_ENVIRONMENTAL_DAMAGE_FIRE", "STRING_ENVIRONMENTAL_DAMAGE_LAVA",
  "STRING_ENVIRONMENTAL_DAMAGE_SLIME", "STRING_SCHOOL_ARCANE", "STRING_SCHOOL_CHAOS", "STRING_SCHOOL_CHROMATIC",
  "STRING_SCHOOL_COSMIC", "STRING_SCHOOL_DIVINE", "STRING_SCHOOL_ELEMENTAL", "STRING_SCHOOL_FIRE",
  "STRING_SCHOOL_FIRESTORM", "STRING_SCHOOL_FLAMESTRIKE", "STRING_SCHOOL_FROST", "STRING_SCHOOL_FROSTFIRE",
  "STRING_SCHOOL_FROSTSTORM", "STRING_SCHOOL_FROSTSTRIKE", "STRING_SCHOOL_HOLY", "STRING_SCHOOL_HOLYFIRE",
  "STRING_SCHOOL_HOLYFROST", "STRING_SCHOOL_HOLYSTORM", "STRING_SCHOOL_HOLYSTRIKE", "STRING_SCHOOL_MAGIC",
  "STRING_SCHOOL_NATURE", "STRING_SCHOOL_PHYSICAL", "STRING_SCHOOL_SHADOW", "STRING_SCHOOL_SHADOWFLAME",
  "STRING_SCHOOL_SHADOWFROST", "STRING_SCHOOL_SHADOWLIGHT", "STRING_SCHOOL_SHADOWSTORM",
  "STRING_SCHOOL_SHADOWSTRIKE", "STRING_SCHOOL_SPELLFIRE", "STRING_SCHOOL_SPELLFROST", "STRING_SCHOOL_SPELLSHADOW",
  "STRING_SCHOOL_SPELLSTORM", "STRING_SCHOOL_SPELLSTRIKE", "STRING_SCHOOL_STORMSTRIKE", "strlower", "strrep",
  "strsplit", "strsub", "strtrim", "TABARDSLOT", "TableHasAnyEntries", "tan", "TANK", "tAppendAll", "tCompare",
  "tContains", "tDeleteItem", "TextToSpeech_GetSelectedVoice", "TextToSpeech_Speak", "time", "tIndexOf", "tinsert",
  "ToggleDropDownMenu", "TransmogLocationMixin", "TransmogPendingInfoMixin", "tremove", "TRINKET0SLOT_UNIQUE",
  "TRINKET1SLOT_UNIQUE", "UIDropDownMenu_AddButton", "UIDropDownMenu_CreateInfo", "UIDropDownMenu_Initialize",
  "UIDropDownMenu_JustifyText", "UIDropDownMenu_SetDisplayMode", "UIDropDownMenu_SetInitializeFunction",
  "UIDropDownMenu_SetText", "UIDropDownMenu_SetWidth", "UIErrorsFrame", "UIMenuButtonStretchMixin", "UIParent",
  "UISpecialFrames", "UnitAffectingCombat", "UnitAttackPower", "UnitAttackSpeed", "UnitAura", "UnitCanAttack",
  "UnitCastingDuration", "UnitCastingInfo", "UnitChannelDuration", "UnitChannelInfo", "UnitClass", "UnitDetailedThreatSituation", "UnitEffectiveLevel",
  "UnitExists", "UnitFactionGroup", "UnitFullName", "UnitGroupRolesAssigned", "UnitGUID", "UnitHasVehicleUI",
  "UnitInBattleground", "UnitInParty", "UnitInRaid", "UnitInRange", "UnitInSubgroup", "UnitInVehicle",
  "UnitIsConnected", "UnitIsDeadOrGhost", "UnitIsGroupAssistant", "UnitIsGroupLeader", "UnitIsPVP",
  "UnitIsPVPFreeForAll", "UnitIsUnit", "UnitIsVisible", "UnitLevel", "UnitName", "UnitOnTaxi", "UnitPartialPower",
  "UnitHealthPercent", "UnitPower", "UnitPowerMax", "UnitPowerPercent", "UnitRace", "UnitRangedDamage", "UnitReaction", "UnitSex", "UnitStagger",
  "UpdateAddOnCPUUsage", "UPPER_LEFT_VERTEX", "UPPER_RIGHT_VERTEX", "Vector2DMixin", "Vector3DMixin",
  "VOICE_WINDOW_ID", "WAISTSLOT", "WeakAuras", "WeakAurasArchive", "WeakAurasCompanion", "WeakAuras_DropDownMenu",
  "WeakAurasOptions", "WeakAurasOptionsPortrait", "WeakAurasOptionsSaved", "WeakAurasOptionsTitleText",
  "WeakAurasProfilingColumnDisplay_OnClick", "WeakAurasProfilingFrame", "WeakAurasProfilingLineMixin",
  "WeakAurasProfilingMixin", "WeakAurasProfilingReport", "WeakAurasProfilingReportMixin",
  "WeakAurasProfilingResultButton_OnClick", "WeakAurasProfilingStopButton_OnClick", "WeakAurasSaved",
  "WeakAurasTimers", "wipe", "WorldFrame", "WrapTextInColorCode", "WRISTSLOT",
}
